### ISSUE TITLE
string.quoted suppert in tree-sitter

### ISSUE THREAD

**Issue by HugoMcPhee** [digitallyserviced/semanticolor#45]
Hi thanks for making semanticolor,

in the tree-sitter update, it looks like "text" is blank when scopeName is "string.quoted",

```javascript
if (utils.isTreeSitter(grammar)) {
  semanticolorGrammar.idForScope = function (scopeName, text) {
  if (scopeName.includes("string") {
    console.log(text) // text is empty
  }
  // ...
}
```

is this a known limitation for tree-sitter?

**Comment by sharedprophet** [comment]
In short, yes.

Fetching the text from TreeSitter has a performance cost, and the grammar checks for the scope at basically every level of the document, from the full text of the whole thing down to individual tokens/words. In order to reduce the performance penalty as much as possible, when I added the text to the call in the grammar to support Semanticolor, I set it up to do so only for leaf nodes (individual words/tokens).

Generally the text isn’t needed for strings as they tend to always be set to the same color. Are you trying to set up a configuration that needs different colors for each string constant?

**Comment by HugoMcPhee** [comment]
thanks for the quick reply,

oh okay that makes sense, yes am using custom state management relying on typed strings, similar to:
```javascript
const myScore = getState({ type: "gameStats", prop: "myScore" })
```
where having the myScore variable and string match colors has been useful.

also have no current issues with textmate aside from code-folding, although had switched to be future-proof

a small sidenote, I noticed other keywords (maybe nested-properties?) weren't colored in treesiter until "source" was set to colored.
assuming that's for a simmilar reason?

**Comment by sharedprophet** [comment]
Or create objects with your string values as props?

```js
const types = {
  gameStats = "gameStats",
  //...
};
const props = {
  myScore = "myScore",
  //...
};

const myScore = getState({ type: types.gameStats, prop: props.myScore });
```

**Comment by HugoMcPhee** [comment]
thanks for the tips and example, that's good to know a custom plugin solution may still be possible later
